PimpMyRide.Web/Areas/Moderator/Controllers/CarsController.cs
namespace PimpMyRide.Web.Areas.Moderator.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using PimpMyRide.Services.Moderator.Contracts;

    public class CarsController : BaseModeratorController
    {
        private readonly IModeratorCarsService carsService;

        public CarsController(IModeratorCarsService carsService)
        {
            this.carsService = carsService;
        }

        public IActionResult List()
        {
            var inActiveCars = this.carsService.GetAllInActive();

            return this.View(inActiveCars);
        }

        public IActionResult Details(int id)
        {
            var car = this.carsService.GetDetails(id);

            return this.View(car);
        }

        public IActionResult Approve(int id)
        {
            this.carsService.Approve(id);

            this.TempData[WebConstants.TempDataSuccessMessageKey] = "Car has been succsessfully aproved.";

            return this.RedirectToAction("List");
        }

        public IActionResult Delete(int id)
        {
            this.carsService.Delete(id);

            this.TempData[WebConstants.TempDataErrorMessageKey] = "Car has been deleted.";

            return this.RedirectToAction("List");
        }
    }
}

PimpMyRide.Web/Controllers/CarsController.cs
namespace PimpMyRide.Web.Controllers
{
    using System.Threading.Tasks;
    using Infrastructure.Extensions;
    using Infrastructure.Filters;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using PimpMyRide.Services.Contracts;
    using PimpMyRide.Services.Models;

    [Authorize]
    public class CarsController : Controller
    {
        private readonly ICarService carService;

        public CarsController(ICarService carService)
        {
            this.carService = carService;
        }

        public IActionResult Add()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Add(CarServiceModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var picture = model.Picture == null
                ? null
                : Task.Run(async () => await model.Picture.ToByteArrayAsync()).Result;

            var user = this.carService.GetOwner(this.User.Identity.Name);

            var carId =
                this.carService.Add(user
                , model.Make,
                model.CarModel,
                model.YearOfProduction,
                model.EngineType,
                model.BodyType,
                model.TotalPrice,
                model.Description,
                picture);

            return this.RedirectToAction("Details", "Cars", new { Id = carId });
        }

        public IActionResult Edit(int id)
        {
            if (!this.carService.Exists(id))
            {
                return this.NotFound();
            }

            if (!this.User.IsInRole(WebConstants.AdministratorRole))
            {
                var isOwner = this.carService.IsOwner(id, this.User.Identity.Name);

                if (!isOwner)
                {
                    return this.NotFound();
                }
            }

            var car = this.carService.GetCar(id);

            return this.View(car);
        }

        [HttpPost]
        public IActionResult Edit(int id, CarServiceModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            if (!this.User.IsInRole(WebConstants.AdministratorRole))
            {
                var isOwner = this.carService.IsOwner(id, this.User.Identity.Name);

                if (!isOwner)
                {
                    return this.NotFound();
                }
            }

            var picture = model.Picture == null
                 ? null
                 : Task.Run(async () => await model.Picture.ToByteArrayAsync()).Result;

            var carId = this.carService.Edit(
                  id,
                  model.Make,
                  model.CarModel,
                  model.YearOfProduction,
                  model.EngineType,
                  model.BodyType,
                  model.TotalPrice,
                  model.Description,
                  picture);


            return this.RedirectToAction("Details", "Cars", new { Id = carId });
        }

        [AllowAnonymous]
        [ViewCounFilter]
        public IActionResult Details(int id)
        {
            if (!this.carService.Exists(id))
            {
                return this.NotFound();
            }

            if (!this.carService.IsActive(id) &&
                (!this.User.IsInRole(WebConstants.AdministratorRole) &&
                !this.User.IsInRole(WebConstants.ModeratorRole) &&
                !this.carService.IsOwner(id, this.User.Identity.Name)))
            {
                return this.NotFound();
            }

            var car = this.carService.GetCarDetails(id);

            return this.View(car);
        }

        public IActionResult Delete(int id)
        {
            if (!this.User.IsInRole(WebConstants.AdministratorRole))
            {
                var isOwner = this.carService.IsOwner(id, this.User.Identity.Name);

                if (!isOwner)
                {
                    return this.NotFound();
                }
            }

            this.carService.Delete(id);

            // should redirect to my cars view

            return this.RedirectToAction("All");
        }

        [AllowAnonymous]
        public IActionResult All(string make, string model, int? from, int? to)
        {
            if (make == null && model == null && from == null && to == null)
            {
                var cars = this.carService.GetAll();

                return this.View(cars);
            }

            var carsSearched = this.carService.GetAllSearch(make, model, from, to);

            return this.View(carsSearched);
        }
    }
}

PimpMyRide.Web/Controllers/PartsController.cs
namespace PimpMyRide.Web.Controllers
{
    using System.Threading.Tasks;
    using Infrastructure.Extensions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using PimpMyRide.Services.Contracts;
    using PimpMyRide.Services.Models;

    [Authorize]
    public class PartsController : Controller
    {
        private readonly IPartService partService;

        public PartsController(IPartService partService)
        {
            this.partService = partService;
        }

        public IActionResult Add(int id)
        {
            if (!this.partService.CarExists(id))
            {
                return this.NotFound();
            }

            if (!this.User.IsInRole(WebConstants.AdministratorRole) &&
                !this.partService.IsOwner(id, this.User.Identity.Name))
            {
                return this.NotFound();
            }

            return this.View();
        }

        [HttpPost]
        public IActionResult Add(int id, PartCrudServiceModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            if (!this.partService.CarExists(id))
            {
                return this.NotFound();
            }

            if (!this.User.IsInRole(WebConstants.AdministratorRole) &&
                !this.partService.IsOwner(id, this.User.Identity.Name))
            {
                return this.NotFound();
            }

            var picture = model.Picture == null
                ? null
                : Task.Run(async () => await model.Picture.ToByteArrayAsync()).Result;

            this.partService.AddPart(id, model.Name, model.Price, model.Description, picture);

            return this.RedirectToAction("Details", "Cars", new { id = id });
        }

        public IActionResult Edit(int id)
        {
            if (!this.partService.PartExists(id))
            {
                return this.NotFound();
            }

            var part = this.partService.GetPart(id);

            if (!this.User.IsInRole(WebConstants.AdministratorRole) &&
                !this.partService.IsOwner(part.CarId, this.User.Identity.Name))
            {
                return this.NotFound();
            }

            return this.View(part);
        }

        [HttpPost]
        public IActionResult Edit(int id, PartCrudServiceModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            if (!this.partService.PartExists(id))
            {
                return this.NotFound();
            }

            var part = this.partService.GetPart(id);

            if (!this.User.IsInRole(WebConstants.AdministratorRole) &&
                !this.partService.IsOwner(part.CarId, this.User.Identity.Name))
            {
                return this.NotFound();
            }

            var picture = model.Picture == null
                ? null
                : Task.Run(async () => await model.Picture.ToByteArrayAsync()).Result;

            this.partService.EditPart(id, model.Name, model.Price, model.Description, picture);

            return this.RedirectToAction("Details", "Cars", new { id = part.CarId });
        }

        public IActionResult Delete(int id)
        {
            if (!this.partService.PartExists(id))
            {
                return this.NotFound();
            }

            var part = this.partService.GetPart(id);

            if (!this.User.IsInRole(WebConstants.AdministratorRole) &&
                !this.partService.IsOwner(part.CarId, this.User.Identity.Name))
            {
                return this.NotFound();
            }

            this.partService.DeletePart(id);

            return this.RedirectToAction("Details", "Cars", new { id = part.CarId });
        }
    }
}

PimpMyRide.Web/Views/Componets/CarListViewComponent.cs
namespace PimpMyRide.Web.Views.Componets
{
    using System.Collections.Generic;
    using Microsoft.AspNetCore.Mvc;
    using PimpMyRide.Services.Models;

    public class CarListViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(IEnumerable<CarListServiceModel> cars)
        {
            return this.View(cars);
        }
    }
}

PimpMyRide.Web/Views/Componets/PartListViewComponent.cs
namespace PimpMyRide.Web.Views.Componets
{
    using Microsoft.AspNetCore.Mvc;
    using PimpMyRide.Services.Contracts;

    public class PartListViewComponent : ViewComponent
    {
        private readonly IPartService partService;

        public PartListViewComponent(IPartService partService)
        {
            this.partService = partService;
        }

        public IViewComponentResult Invoke(int id)
        {
            var parts = this.partService.GetParts(id);

            return this.View(parts);
        }
    }
}

PimpMyRide.Web/Views/Cars/Add.cshtml
@model CarServiceModel
@{
    ViewData["Title"] = "Add new Car";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />

<div class="row">
    <div class="col-md-4 col-md-offset-4 text-center">
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Make"></label>
                <input asp-for="Make" class="form-control" />
                <span asp-validation-for="Make" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarModel"></label>
                <input asp-for="CarModel" class="form-control" />
                <span asp-validation-for="CarModel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearOfProduction"></label>
                <select asp-for="YearOfProduction" class="form-control">
                    @for (int year = DataConstants.MaxYear; year >= DataConstants.MinYear; year--)
            {
                <option value="@year">@year</option>
    }
                </select>
                <span asp-validation-for="YearOfProduction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EngineType"></label>
                <select asp-for="EngineType" asp-items="@Html.GetEnumSelectList(typeof(EngineType))" class="form-control"></select>
                <span asp-validation-for="EngineType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BodyType"></label>
                <select asp-for="BodyType" asp-items="@Html.GetEnumSelectList(typeof(BodyType))" class="form-control"></select>
                <span asp-validation-for="BodyType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPrice"></label>
                <input asp-for="TotalPrice" min="1" step="1" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" rows="4" style="resize: vertical" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Picture"></label>
                <input asp-for="Picture" class="form-control btn btn-default" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <button type="button" onclick="goBack()" class="btn btn-default">Cancel</button>
            <button type="submit" class="btn btn-success">Add</button>
        </form>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

PimpMyRide.Web/Views/Cars/All.cshtml
@model IEnumerable<CarListServiceModel>

<div style="margin-bottom: 30px;" class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="input-group" id="adv-search">
                <p class="form-control">Search for cars</p>
                <div class="input-group-btn">
                    <div class="btn-group" role="group">
                        <div class="dropdown dropdown-lg">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></button>
                            <div class="dropdown-menu dropdown-menu-right" role="menu">
                                <form class="form-horizontal col-md-8 col-md-offset-2">
                                    <div class="form-group text-center">
                                        <label for="make">Make</label>
                                        <input class="form-control" name="make" type="text" id="make" />
                                    </div>
                                    <div class="form-group text-center">
                                        <label for="model">Model</label>
                                        <input class="form-control" name="model" type="text" id="model" />
                                    </div>
                                    <div class="form-group text-center">
                                        <label for="yearofprod">Year of Production</label>
                                        <p>From:</p> <input class="form-control" name="from" max="2017" min="1985" step="1" type="number" id="yearofprod" />
                                        <br />
                                        <br />
                                        <p>To:</p> <input class="form-control" name="to" max="2017" min="1985" step="1" type="number" />
                                    </div>
                                    <div class="text-center"><button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button></div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    @await Component.InvokeAsync("CarList", Model)
</div>

PimpMyRide.Web/Views/Cars/Details.cshtml
@model CarDetailsServiceModel



@if (TempData.Keys.Contains(WebConstants.TempDataErrorMessageKey))
{
    <div class="well well-sm text-center" style="color: red">@TempData[WebConstants.TempDataErrorMessageKey]</div>
}

@if (TempData.Keys.Contains(WebConstants.TempDataSuccessMessageKey))
{
    <div class="well well-sm text-center" style="color: green">@TempData[WebConstants.TempDataSuccessMessageKey]</div>
}

<div class="row">
    <div class="col-md-5">
        <p>@Model.Views преглеждания</p>
        <div style="margin-bottom: 20px" class="row text-center">
            @if (Model.Picture == null)
            {
                <img src="~/images/noImage.jpg" height="230" width="360" />
            }
            else
            {
                <img src="@Model.Picture" />
            }
        </div>
        <div class="text-center">
            @if (User.IsInRole(WebConstants.AdministratorRole) || Model.OwnerUsername == User.Identity.Name)
            {

                <a asp-area=""
                   asp-controller="Cars"
                   asp-action="Edit"
                   asp-all-route-data="@(new Dictionary<string, string> {{"id", @Model.Id.ToString()}})"
                   class="btn btn-sm btn-warning">Edit</a>
                <a asp-area=""
                   asp-controller="Cars"
                   asp-action="Delete"
                   asp-all-route-data="@(new Dictionary<string, string> {{"id", @Model.Id.ToString()}})"
                   class="btn btn-sm btn-danger">Delete</a>
            }
            @if (Model.OwnerUsername == User.Identity.Name)
            {
                <a class="btn btn-sm btn-success"
                   asp-area=""
                   asp-controller="Parts"
                   asp-action="Add"
                   asp-route-id="@Model.Id">
                    Add part
                </a>
            }
        </div>
        <div class="well row">
            <div class="col-md-6">
                <p><strong>Make</strong> : @Model.Make</p>
                <p><strong>Model</strong> : @Model.Model</p>
                <p><strong>Engine</strong> : @Model.EngineType.ToString()</p>
                <p><strong>Body type</strong> : @Model.BodyType.ToString()</p>
                <p><strong>Year Of Production</strong> : @Model.YearOfProduction</p>
            </div>
            <div class="col-md-6">
                <p><strong>Description</strong> : @(Model.Description ?? "No description.")</p>
            </div>
        </div>
        <div class="well row">
            <p><strong>Added on</strong> : @Model.Added.ToShortDateString()</p>
            <p><strong>Owner</strong> : @Model.Owner</p>
            <p><strong>Tel.</strong> : @(Model.PhoneNumber ?? "No info.")</p>
        </div>
        <hr />
    </div>

    <div class="col-md-6 col-md-offset-1">
        @await Component.InvokeAsync("PartList", new { id = @Model.Id })
    </div>
</div>

PimpMyRide.Web/Views/Cars/Edit.cshtml
@model CarServiceModel
@{
    ViewData["Title"] = "Edit Car";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />

<div class="row">
    <div class="col-md-4 col-md-offset-4 text-center">
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Make"></label>
                <input asp-for="Make" class="form-control" />
                <span asp-validation-for="Make" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarModel"></label>
                <input asp-for="CarModel" class="form-control" />
                <span asp-validation-for="CarModel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearOfProduction"></label>
                <select asp-for="YearOfProduction" class="form-control">
                    @for (int year = DataConstants.MaxYear; year >= DataConstants.MinYear; year--)
            {
                <option value="@year">@year</option>
    }
                </select>
                <span asp-validation-for="YearOfProduction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EngineType"></label>
                <select asp-for="EngineType" asp-items="@Html.GetEnumSelectList(typeof(EngineType))" class="form-control"></select>
                <span asp-validation-for="EngineType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BodyType"></label>
                <select asp-for="BodyType" asp-items="@Html.GetEnumSelectList(typeof(BodyType))" class="form-control"></select>
                <span asp-validation-for="BodyType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPrice"></label>
                <input asp-for="TotalPrice" min="1" step="1" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" rows="4" style="resize: vertical" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Picture"></label>
                <input asp-for="Picture" class="form-control btn btn-default" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <button type="button" onclick="goBack()" class="btn btn-default">Cancel</button>
            <button type="submit" class="btn btn-warning">Edit</button>
        </form>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}